milk/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

app_name = 'milk'

urlpatterns = [
    path('', views.TrainView.as_view(), name='train'),
    path('upload/', views.UploadView.as_view(), name='upload'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('progress/<int:pk>/', views.progress, name='progress'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('milk.urls')),
]

milk/models.py
from django.db import models


class Progress(models.Model):
    """進捗を表すモデル"""
    num = models.IntegerField('進捗', default=0)
    target = models.CharField('フォルダ', max_length=200)
    nb_train = models.IntegerField('訓練枚数', default=0)


class History(models.Model):
    """model.fitのhistory"""
    progress = models.ForeignKey(Progress, on_delete=models.CASCADE)
    epochs = models.IntegerField('epoch', default=0)
    acc = models.FloatField('accuracy', default=0)
    val_acc = models.FloatField('validation_accuracy', default=0)

    fpr = models.CharField(max_length=5000)
    tpr = models.CharField(max_length=5000)
    auc = models.FloatField('auc', default=0)

milk/forms.py
from django import forms
from .models import Progress


class DirectoryPathForm(forms.ModelForm):
    class Meta:
        model = Progress
        fields = ("target", )


class ImageUploadForm(forms.Form):
    file = forms.ImageField(label='画像ファイル')

milk/views.py
import time
from multiprocessing import Process

from django.shortcuts import redirect, render, get_object_or_404
from django.views import generic

from .models import Progress, History
from .forms import ImageUploadForm, DirectoryPathForm
from .lib import predict, load_data
import numpy as np
from PIL import Image
import cv2

from sklearn.metrics import roc_curve, auc
from itertools import cycle
from scipy import interp

import os
import json
import matplotlib.pyplot as plt

from keras import backend as k

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = os.path.join(BASE_DIR, 'milk/static')

class UploadView(generic.FormView):
    template_name = 'milk/upload.html'
    form_class = ImageUploadForm

    def form_valid(self, form):
        file = form.cleaned_data['file']
        img = Image.open(file).resize((28, 28)).convert('L')

        img_array = np.asarray(img) / 255
        img_array = img_array.reshape(1, 784)

        context = {
            'result': predict(img_array),
        }
        return render(self.request, 'milk/result.html', context)


class TrainView(generic.CreateView):
    model = Progress
    form_class = DirectoryPathForm
    template_name = 'milk/train.html'

    def form_valid(self, form):
        progress_instance = form.save()
        p = Process(target=update, args=(progress_instance.pk, progress_instance.target), daemon=True)
        p.start()

        return redirect('milk:progress', pk=progress_instance.pk)


class HomeView(generic.CreateView):
    """処理の開始ページ"""
    model = Progress
    form_class = DirectoryPathForm
    template_name = 'milk/home.html'

    def form_valid(self, form):
        print('test: ', form.instance.num)
        progress_instance = form.save()
        p = Process(target=update, args=(progress_instance.pk,), daemon=True)
        p.start()
        return redirect('milk:progress', pk=progress_instance.pk)


def update(pk, directory):
    """裏側で動いている時間のかかる処理"""
    progress = get_object_or_404(Progress, pk=pk)
    (x_train, y_train), (x_test, y_test), model = load_data(directory)

    progress.nb_train = len(x_train)

    nb_classes = y_train.shape[1]
    epochs = 30
    batch_size = 16

    for epoch in range(epochs):
        hist = model.fit(x_train, y_train,
                            epochs=1,
                            batch_size=batch_size,
                            validation_data=(x_test, y_test),
                            verbose=0
                            )

        y_prediction = model.predict(x_train)

        all_fpr, mean_tpr, auc = roc(y_train, y_prediction, nb_classes)

        confusion_visualize(x_train, np.argmax(y_train, axis=1), y_prediction, [i for i in range(nb_classes)])

        # acc, val_accを数値で受け取る
        progress.history_set.create(
            acc=hist.history['acc'][0],
            val_acc=hist.history['val_acc'][0],
            epochs=epoch,
            fpr=json.dumps(all_fpr),
            tpr=json.dumps(mean_tpr),
            auc=auc
        )


        progress.num = int( (epoch+1) * 100/epochs )  # progress.htmlのprogress barに表示する．Max100に広げる
        progress.save()

    model.save('model.h5')
    os.remove(MEDIA_ROOT+'/milk/model.png')

def progress(request, pk):
    """現在の進捗ページ"""
    progress = get_object_or_404(Progress, pk=pk)
    history = progress.history_set.all()
    if len(list(history.values_list('fpr'))) != 0:
        pca_str_list = json.loads(list(history.values_list('fpr'))[0][0])
        pca_int_list = [float(x) for x in pca_str_list]
        fpr = pca_int_list

        pca_str_list = json.loads(list(history.values_list('tpr'))[0][0])
        pca_int_list = [float(y) for y in pca_str_list]
        tpr = pca_int_list

    else:
        fpr = [0]
        tpr = [0]

    context = {
        'progress': progress,
        'history_list': history,
        'epochs': list(history.values_list('epochs', flat=True)),
        'acc_list': list(history.values_list('acc', flat=True)),
        'val_acc_list': list(history.values_list('val_acc', flat=True)),
        'fpr': fpr,
        'tpr': tpr,
        'auc': list(history.values_list('auc', flat=True))
    }
    return render(request, 'milk/progress.html', context)

def roc(y_test, y_prediction, num_classes):
    # Compute ROC curve and ROC area for each class
    fpr = dict()
    tpr = dict()
    roc_auc = dict()

    for i in range(num_classes):
        fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_prediction[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])

    # Compute macro-average ROC curve and ROC area
    # First aggregate all false positive rates
    all_fpr = np.unique(np.concatenate([fpr[i] for i in range(num_classes)]))

    # Then interpolate all ROC curves at this points
    mean_tpr = np.zeros_like(all_fpr)
    for i in range(num_classes):
        mean_tpr += interp(all_fpr, fpr[i], tpr[i])

    # Finally average it and compute AUC
    mean_tpr /= num_classes

    return list(all_fpr), list(mean_tpr), auc(all_fpr, mean_tpr)

def confusion_visualize(images, labels, predict_prob, class_names):
    _, height, width, _ = images.shape
    frame_percent = 2  # outframe
    frame = int((height + width) / 2 * (frame_percent/100)) + 1
    nb_classes = len(class_names)

    ffamily_title = cv2.FONT_HERSHEY_TRIPLEX
    linetype = cv2.LINE_AA
    
    result = np.zeros((height*nb_classes, width*nb_classes, 3))
    matrix = np.zeros((height*nb_classes, width*nb_classes, 3))

    max_predict_num = 0

    if np.max(images) <= 1:
        images *= 255
    predict_cls = np.argmax(predict_prob, axis=1)
    for true_index in range(nb_classes):
        for predict_index in range(nb_classes):
            index_range = np.where((labels==true_index) & (predict_cls==predict_index))
            predict_num = len(index_range[0])  # matrix number
            if max_predict_num < predict_num:
                max_predict_num = predict_num
            
            prob = predict_prob[index_range]
            one_picture = np.zeros((height, width, 3))
            one_picture_matrix = np.zeros((height, width, 3)).astype('uint8')
            if true_index == predict_index:
                one_picture[:, :, 1] = 255
                one_picture_matrix[:, :, 1] = 255
            else:
                one_picture[:, :, 2] = 255
                one_picture_matrix[:, :, 2] = 255

            one_picture_matrix[frame:-frame, frame:-frame] = 0
            if len(prob) == 0:
                one_picture[frame:-frame, frame:-frame] = np.zeros((height-2*frame, width-2*frame, 3))
                
            else:
                sort_range = np.argsort(prob[:, predict_index])[::-1]
                one_picture[frame:-frame, frame:-frame] = images[index_range[0][sort_range][0]][frame:-frame, frame:-frame]
                cv2.putText(one_picture_matrix, str(predict_num), (width//4, height//2), ffamily_title, 0.5, (255,255,255), 1, linetype)
                # one_picture_matrix[frame:-frame, frame:-frame, 0] = predict_num

            result[height*true_index:height*(true_index+1), width*predict_index:width*(predict_index+1)] = one_picture
            matrix[height*true_index:height*(true_index+1), width*predict_index:width*(predict_index+1)] = one_picture_matrix.copy()
        
        # matrix[:, :, 0] *= (255/predict_num)

    cv2.imwrite(MEDIA_ROOT+'/milk/confusion_visualize.png', result)
    cv2.imwrite(MEDIA_ROOT+'/milk/confusion_matrix.png', matrix)

milk/templates/milk/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>手書き数字判別アプリ</title>
  </head>
  <body>
    <div class="container">
      <!-- ナビバー -->
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'milk:train' %}">賢くなる</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'milk:upload' %}">当てちゃう</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'milk:home' %}">プログラムテスト</a>
        </li>
      </ul>

      {% block content %}{% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

milk/templates/milk/build_model.html
{% extends 'milk/base.html' %}
{% block content %}
<p>{{ target_directory }} ファルダ内の画像をアップロードします。</p>
{% load static%}
<img src="{% static "milk/model.png" %}">
<p>ネットワーク</p>
<p>{{ files }} </p>
<p> 画像枚数: , 入力画像サイズ:　</p>
<p>学習経過</p>
<p>学習結果</p>
<p>ROC</p>
{% endblock %}

milk/templates/milk/home.html
{% extends 'milk/base.html' %}
{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">処理の開始</button>
</form>
{% endblock %}

milk/templates/milk/progress.html
{% extends 'milk/base.html' %}

{% block content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>


{% if progress.num == 100 %}
  <div>
    処理終了
  </div>

  <div class="container" style="width:50%">
    <canvas id="accuracy" width="250px" height="150px"></canvas>
    <script>
      // accuracy
      var ctx = document.getElementById('accuracy').getContext('2d');
      var accuracy = new Chart(ctx, {
        type: 'line',
        data: {
          labels: {{ epochs }},
          datasets: [{
            label: 'acc',
            data: {{ acc_list }},
            backgroundColor: "rgba(153,255,51,0.4)",
            borderColor: "rgba(153,255,51,0.4)",
            lineTension: 0
          }, {
            label: 'val_acc',
            data: {{ val_acc_list }},
            backgroundColor: "rgba(255,153,0,0.4)",
            borderColor: "rgba(255,153,0,0.4)",
            lineTension: 0
          }]
        }
      });
    </script>
  </div>

  <div class="container" style="width:50%">
    <canvas id="roc" width="250px" height="250px"></canvas>
    <script>
      // ROC
      var line_y = d3.range(0, 1, 1/{{fpr}}.length);
      var ctx = document.getElementById('roc').getContext('2d');
      var roc = new Chart(ctx, {
        type: 'line',
        data: {
          labels: {{ fpr }},
          datasets: [{
            label: 'ROC',
            data: {{ tpr }},
            backgroundColor: "rgba(153,255,51,0.4)",
            borderColor: "rgba(153,255,51,0.4)",
            lineTension: 0
          }, {
            label: 'y=x',
            data: line_y,
            lineTension: 0,
            fill: false,
            pointRadius: 0,
            borderDash: [0.1, 0.1],
            borderColor: "rgb(0,0,0)"
          }]
        },
        options: {
          legend: {
            labels: {
              filter: function (item, chart) {
                return !item.text.includes('y=x');
              }
            }
          }
        }
      });
    </script>
  </div>


  <script>

    // scatter plot data
    function genData(){
        var size = getRandomInt( 20, 100 );
        var data = [];
        for( var i = 0; i < size; i++ ) {
            var x = getRandomInt( 0, 100 );
            var y = getRandomInt( 0, 100 );
            data.push( { x:x, y:y });
        }
        return data;
    };

  </script>


{% else %}
<meta http-equiv="refresh" content="3">

  {% if progress.num > 0 %}
  {% load static %}
  <img src="{% static "milk/confusion_visualize.png" %}">
  <img src="{% static "milk/confusion_matrix.png" %}">
    <div>train_size: {{ progress.nb_train }}</div>

    <div class="progress">
      <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuenow="{{ progress.num }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress.num }}%"></div>
    </div>

  <div class="container" width=50%>
    <canvas id="accuracy" width="250" height="150"></canvas>
    <script>
      // accuracy
      var ctx = document.getElementById('accuracy').getContext('2d');
      var accuracy = new Chart(ctx, {
        type: 'line',
        data: {
          labels: {{ epochs }},
          datasets: [{
            label: 'acc',
            data: {{ acc_list }},
            backgroundColor: "rgba(153,255,51,0.4)",
            borderColor: "rgba(153,255,51,0.4)",
            lineTension: 0
          }, {
            label: 'val_acc',
            data: {{ val_acc_list }},
            backgroundColor: "rgba(255,153,0,0.4)",
            borderColor: "rgba(255,153,0,0.4)",
            lineTension: 0
          }]
        }
      });
    </script>
  </div>


    <canvas id="roc" width="200" height="200"></canvas>
    <script>
      // ROC
      var line_y = d3.range(0, 1, 1/{{fpr}}.length);
      var ctx = document.getElementById('roc').getContext('2d');
      var roc = new Chart(ctx, {
        type: 'line',
        data: {
          labels: {{ fpr }},
          datasets: [{
            label: 'ROC',
            data: {{ tpr }},
            backgroundColor: "rgba(153,255,51,0.4)",
            borderColor: "rgba(153,255,51,0.4)",
            lineTension: 0
          }, {
            label: 'y=x',
            data: line_y,
            lineTension: 0,
            fill: false,
            pointRadius: 0,
            borderDash: [0.1, 0.1],
            borderColor: "rgb(0,0,0)"
          }]
        }
      });
    </script>
    <canvas id="pca" width="200" height="200"></canvas>
    <script>
      // PCA plot
      var ctx = document.getElementById('pca').getContext('2d');
      var pca = new Chart(ctx, {
        type: 'line',
        data: {
          labels: {{ pca_x }},
          datasets: [{
            label: 'pca',
            data: {{ pca_y }},
            backgroundColor: "rgba(225,95,150, 1)",
            borderColor: "rgba(255,255,255,1)",
            lineTension: 0
          }]
        }
      });

      // scatter plot data
      function genData(){
          var size = getRandomInt( 20, 100 );
          var data = [];
          for( var i = 0; i < size; i++ ) {
              var x = getRandomInt( 0, 100 );
              var y = getRandomInt( 0, 100 );
              data.push( { x:x, y:y });
          }
          return data;
      };
    </script>


  {% else %}
    <div>データロード中...</div>
    {% load static %}
    <img src="{% static "milk/model.png" %}">

  {% endif %}

{% endif %}

{% endblock %}

milk/templates/milk/result.html
{% extends 'milk/base.html' %}
{% block content %}
<p>{{ result }} と判別されました。</p>
{% endblock %}

milk/templates/milk/train.html
{% extends 'milk/base.html' %}
{% block content %}
<form action="" method="POST">
  {{ form.as_table }}<hr>
  {% csrf_token %}
  <input type="submit" class="btn btn-outline-primary btn-lg" value="送信する">
</form>
{% endblock %}

milk/templates/milk/upload.html
{% extends 'milk/base.html' %}
{% block content %}
<form action="" method="POST" enctype='multipart/form-data'>
  {{ form.file }}<hr>
  {% csrf_token %}
  <input type="submit" class="btn btn-outline-primary btn-lg" value="送信する">
</form>
{% endblock %}